### PR TITLE
add issue template for working group call agendas

### PR DESCRIPTION
**Pull request by whoabuddy**
This issue template stems from my [comment on call 23](https://github.com/stacksgov/pm/issues/95#issuecomment-690398514) where I proposed a slight structure change to how we are handling the agendas moving forward.

Up until now, we have been compiling a list of issues into the agenda with various comments about their status, but as the list expands, it creates an extra burden that often delays the creation of the agenda.

When cloning the previous week's agenda, it requires:
- revisiting each issue listed to check the status
- if open, creating a quick summary, question, or action item related to it
- if closed, removing it from the agenda
- adding any new issues added since the last meeting

This also misplaces some information about each issue into the agenda, which may never make its way back into the issue.

To fix this, I propose creating a very basic meeting agenda template that covers the following points, with links back to each issue label and therefore the individual issues themselves for comments/updates/etc.
- Meeting Details
- Standup Updates
- Stacks Foundation Updates
- Action Items
- Discussion Items
- Miscellaneous Items

You can see a copy of the template in commit a6cc23b and I welcome any feedback or suggestions!

### CODE REVIEW

**Review by Charletta — COMMENTED** [review]
I like this template flow. It is pretty straight forward especially with the comments added.

**Comment by lrettig** [comment]
Cool! Any reason this is in yml format as opposed to md? Can we link to this from the SOP doc?

**Comment by whoabuddy** [comment]
@lrettig That's from me mixing up the template with `config.yml` in [the GitHub instructions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository), good catch! Fixed in 55b6267.

To the SOP doc question, yes, that's one of my next targets after we establish the new flow. 

@Charletta and @HaroldDavis3 thanks for the feedback!

**Comment by whoabuddy** [comment]
Merging this in to create an agenda for today's governance meeting!

**Pull request merged**
